config/routes.rb
Rails.application.routes.draw do
  get 'home/checkr'

  get 'home/flynn'

  get 'home/sparks'

  root 'home#page_accueil'



  resources :home

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def checkr
  end

  def flynn
  end

  def sparks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/checkr.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Home Checker</title>
</head>

<header>
    <div id="conteneur1">
        <div class="container">
                <img src="checklogo.jpg" href=https://checkr.com>
                <nav class="primary-nav" role="navigation">
                <ul id="menu-primary-navigation" class="primary-nav"><li class="dropdown menu-product"><a class="dropdown-toggle " data-toggle="dropdown" data-target="#" href="https://checkr.com/product/">Product <b class="caret"></b></a>
<ul class="dropdown-menu">
    <li class="menu-overview"><a class="" href="https://checkr.com/product/">Overview</a></li>
    <li class="menu-screenings"><a class="" href="https://checkr.com/product/screenings/">Screenings</a></li>
    <li class="menu-compliance"><a class="" href="https://checkr.com/product/compliance/">Compliance</a></li>
    <li class="menu-security"><a class="" href="https://checkr.com/product/security/">Security</a></li>
</ul>
</li>
<li class="dropdown menu-industries"><a class="dropdown-toggle " data-toggle="dropdown" data-target="#" href="https://checkr.com/industries/">Industries <b class="caret"></b></a>
<ul class="dropdown-menu">
    <li class="menu-overview"><a class="" href="https://checkr.com/industries/">Overview</a></li>
    <li class="menu-contact-centers"><a class="" href="https://checkr.com/industries/contact-centers/">Contact Centers</a></li>
    <li class="menu-financial-services"><a class="" href="https://checkr.com/industries/financial-services/">Financial Services</a></li>
    <li class="menu-retail-hospitality"><a class="" href="https://checkr.com/industries/retail-hospitality/">Retail &amp; Hospitality</a></li>
    <li class="menu-healthcare"><a class="" href="https://checkr.com/industries/healthcare/">Healthcare</a></li>
    <li class="menu-non-profit"><a class="" href="https://checkr.com/industries/nonprofit/">Non Profit</a></li>
    <li class="menu-staffing"><a class="" href="https://checkr.com/industries/staffing/">Staffing</a></li>
    <li class="menu-on-demand-economy"><a class="" href="https://checkr.com/industries/on-demand-economy/">On-Demand Economy</a></li>
    <li class="menu-manufacturing"><a class="" href="https://checkr.com/industries/manufacturing/">Manufacturing</a></li>
    <li class="menu-software-technology"><a class="" href="https://checkr.com/industries/software-and-technology/">Software &amp; Technology</a></li>
    <li class="menu-small-business"><a class="" href="https://checkr.com/industries/small-business/">Small Business</a></li>
    <li class="menu-p2p-marketplaces"><a class="" href="https://checkr.com/industries/p2p-marketplaces/">P2P Marketplaces</a></li>
</ul>
</li>
<li class="dropdown menu-resources"><a class="dropdown-toggle " data-toggle="dropdown" data-target="#" href="https://checkr.com/resources/">Resources <b class="caret"></b></a>
<ul class="dropdown-menu">
    <li class="menu-overview"><a class="" href="https://checkr.com/resources/">Overview</a></li>
    <li class="menu-guides-white-papers"><a class="" href="https://checkr.com/resources/white-papers/">Guides &amp; White Papers</a></li>
    <li class="menu-faq"><a class="" href="https://checkr.com/resources/faq/">FAQ</a></li>
</ul>
</li>
</ul>           </nav>

            <nav class="top-nav" role="navigation">
                <ul id="menu-top-menu" class="top-menu">
                    <a class="menu-i-am-an-applicant"></a> <a class="" href="https://applicant.checkr.com/">I Am an Applicant</a>
 <a class="menu-api-docs"><a class="" href="https://docs.checkr.com/">API &amp; Docs</a>
 <a class="menu-about-us"><a class="" href="https://checkr.com/about/">About Us</a>
 <a class="menu-careers"><a class="" href="https://checkr.com/careers/">Careers</a>
</ul>           </nav>

            <nav class="right-nav" role="navigation">
                <ul id="right-menu" class="">
                    <li class="menu-log-in"><a target="_blank" href="https://dashboard.checkr.com/login?next=%2Freports">Log In</a></li>
                    <li class="menu-get-started"><a href="https://checkr.com/get-started">Get Started</a></li>
                </ul>
            </nav>
        </div>
    </div>
    </div>
</header>





<div id="conteneur2">
    <div class="element">
<h2>HIRE GREAT PEOPLE. FASTER.</h2>
<p>Checkr provides modern and compliant background checks for global enterprises and startups.</p>
<button type="button">Explore now</button>
    </div>
    <div class="element">
<%= image_tag "checkr.png"%>

    
    </div>
   

</div>

<body>
<div id="conteneur3">
	<div class="element">  
		<h2><cente>More Than 10,000 Businesses Trust Checkr for Their Background Screenings</h2>
		<%= image_tag "instacart.png" %> <%= image_tag "grubhub.gif" %> <%= image_tag "uber.jpeg"%><%= image_tag "postmates.png" %><%= image_tag "zenefits.gif" %><%= image_tag "handy.jpeg" %>
	</div>
    <div class="element">
    	
    	<h2><center>The Next Generation of Background Checks</center></h2>
    	<center><p><%= image_tag "mobile.png" %><br><strong>Mobile-Friendly</strong></br></br>Create a positive applicant experience with simple, mobile-friendly onboarding.</p></center>

    </div>


   
    <div class="element">  
         <h3><center>Tailored to Fit Your Industry’s Needs</center></h3>
    <center><%= image_tag "web1.png"%>
        <%= image_tag "web2.png"%>
    <%= image_tag "web3.png"%>                                        <%= image_tag "web4.png"%>
        <br>
        <%= image_tag "web5.png"%>                                     <%= image_tag "web6.png"%>                                <%= image_tag "web7.png"%>                                 <%= image_tag "web8.png"%></center>
    </br>
    </div>



        <div class="footer">


        <div class="column footer-product">
            <h4>Product</h4>
            <ul id="menu-footer-product" class="menu"><li class="menu-overview"><a href="https://checkr.com/product/">Overview</a></li>
<li class="menu-screenings"><a href="https://checkr.com/product/screenings/">Screenings</a></li>
<li class="menu-compliance"><a href="https://checkr.com/product/compliance/">Compliance</a></li>
<li class="menu-security"><a href="https://checkr.com/product/security/">Security</a></li>
<li class="menu-api-docs"><a href="https://docs.checkr.com/">API &amp; Docs</a></li>
</ul>       </div>

        <div class="column footer-industries">
            <h4>Industries</h4>
            <ul id="menu-footer-industries" class="menu"><li class="menu-overview"><a href="https://checkr.com/industries/">Overview</a></li>
<li class="menu-contact-centers"><a href="https://checkr.com/industries/contact-centers/">Contact Centers</a></li>
<li class="menu-financial-services"><a href="https://checkr.com/industries/financial-services/">Financial Services</a></li>
<li class="menu-retail-hospitality"><a href="https://checkr.com/industries/retail-hospitality/">Retail &amp; Hospitality</a></li>
<li class="menu-healthcare"><a href="https://checkr.com/industries/healthcare/">Healthcare</a></li>
<li class="menu-non-profit"><a href="https://checkr.com/industries/nonprofit/">Non Profit</a></li>
<li class="menu-staffing"><a href="https://checkr.com/industries/staffing/">Staffing</a></li>
<li class="menu-on-demand-economy"><a href="https://checkr.com/industries/on-demand-economy/">On-Demand Economy</a></li>
<li class="menu-manufacturing"><a href="https://checkr.com/industries/manufacturing/">Manufacturing</a></li>
<li class="menu-software-technology"><a href="https://checkr.com/industries/software-and-technology/">Software &amp; Technology</a></li>
<li class="menu-small-business"><a href="https://checkr.com/industries/small-business/">Small Business</a></li>
<li class="menu-p2p-marketplaces"><a href="https://checkr.com/industries/p2p-marketplaces/">P2P Marketplaces</a></li>
<li class="menu-higher-education"><a href="https://checkr.com/industries/higher-education/">Higher Education</a></li>
</ul>       </div>

        <div class="column footer-resources">
            <h4>Resources</h4>
            <ul id="menu-footer-resources" class="menu"><li class="menu-overview"><a href="https://checkr.com/resources/">Overview</a></li>
<li class="menu-white-papers"><a href="https://checkr.com/resources/white-papers/">White Papers</a></li>
<li class="menu-faq"><a href="https://checkr.com/resources/faq/">FAQ</a></li>
<li class="menu-blog"><a href="http://blog.checkr.com/">Blog</a></li>
<li class="menu-engineering-blog"><a href="https://medium.com/checkr">Engineering Blog</a></li>
<li class="menu-applicant-portal"><a href="https://applicant.checkr.com/">Applicant Portal</a></li>
</ul>       </div>

        <div class="column footer-company">
            <h4>Company</h4>
            <ul id="menu-footer-company" class="menu"><li class="menu-partners"><a href="https://checkr.com/partners/">Partners</a></li>
<li class="menu-partner-lead-portal"><a href="http://info.checkr.com/checkr-partner-portal">Partner Lead Portal</a></li>
<li class="menu-about-us"><a href="https://checkr.com/about/">About Us</a></li>
<li class="menu-bounce-back-to-work"><a href="https://checkr.com/bounce-back-to-work/">Bounce Back to Work</a></li>
<li class="menu-careers"><a href="https://checkr.com/careers/">Careers</a></li>
<li class="menu-press"><a href="https://checkr.com/press/">Press</a></li>
</ul>       </div>

        <div class="column footer-connect">
            <h4>Connect</h4>
            <ul>
                <li><a href="mailto:hello@checkr.com">hello@checkr.com</a></li>
                <li><a href="/contact">Contact Us</a></li>
                <li><a href="/get-started">Get Started</a></li>
                <li><a href="https://dashboard.checkr.com/login?next=%2Freports" target="_blank">Log In</a></li>
            </ul>
                <div class="entry-social-connect">
                                <a target="_blank" href="Https://twitter.com/checkr" title="Checkr on Twitter" class="twitter">
                <img src="https://15743-presscdn-0-7-pagely.netdna-ssl.com/wp-content/uploads/2016/01/icon_twitter.svg">
            </a>
                                <a target="_blank" href="Https://www.facebook.com/checkrio/" title="Checkr on Facebook" class="facebook">
                <img src="https://15743-presscdn-0-7-pagely.netdna-ssl.com/wp-content/uploads/2016/01/facebook.svg">
            </a>
                                <a target="_blank" href="Https://www.linkedin.com/company/checkr-com" title="Checkr on Linkedin" class="linkedin">
                <img src="https://15743-presscdn-0-7-pagely.netdna-ssl.com/wp-content/uploads/2016/01/linkedin.svg">
            </a>
                                <a target="_blank" href="Https://www.instagram.com/checkr_" title="Checkr on Instagram" class="instagram">
                <img src="https://15743-presscdn-0-7-pagely.netdna-ssl.com/wp-content/uploads/2016/01/instagram.svg">
            </a>
                                <a target="_blank" href="Https://angel.co/checkr" title="Checkr on Angellist" class="angellist">
                <img src="https://15743-presscdn-0-7-pagely.netdna-ssl.com/wp-content/uploads/2016/01/angellist.svg">
            </a>
            </div>
        </div>

        <div class="footer-info">
            <ul>
                <li><a href="/customer-agreement">Customer Agreement</a></li>
                <li><a href="/privacy-policy">Privacy Policy</a></li>
                <li><a href="/terms-of-service">Terms of Service</a></li>
                <li><a>© 2017 Checkr, Inc.</a></li>
            </ul>
        </div>

        <div class="napbs-seal">
            <a href="https://portal.napbs.com/i4a/member_directory/feResultsListing.cfm?directory_id=12" target="_blank"></a>
        </div>
    </div>
</div>
</div>



</body>
</html>

app/views/home/flynn.html.erb
<header>
		<img src="">

		<ul>
			<ol></ol>	
			<ol></ol>
			<ol></ol>
			<ol></ol>
			<ol></ol>	
		</ul>
	</header

	<div>
<marquee loop="100">Les Dev de St Ouen sont dans le futur </marquee>

	<h1>Throw away the duct tape.
</br>Say hello to Flynn. </h1>	

	<div class="videopresentation">
		<center><video src="https://dl.flynn.io/assets/flynn_demo_2m.mp4"></video></center>
	</div>


	</div>

	<div class="button">
		<ul>
			
    <ol class="case1">
      <a href="#">Apps</a>
    </ol>

    <ol class="case2">
      <a href="#">Manage</a>
    </ol>

    <ol class="case3">
      <a href="#">Databases</a>
    </ol>
  

		</ul>
		
	</div>

	<section class="bordure">

	<div class="section2">
		<h2>Powerful and easy. The way it should be.</h2>

		<p> 
			<strong>Flynn is an open source platform (PaaS) for running applications in production.</strong>
		</br>
		</br>
		It does everything you need, out of the box:
		</br>
		</br>
			<ul class="open">
				<li>Creates running applications directly from your code so there's no need to learn configuration management or build custom stacks for each app</li></br>
				<li>Routes and load balances traffic to every instance of each of your apps
				</li></br>
				<li>Includes built-in Postgres, MySQL, and MongoDB databases with safe, automatic high availability</li></br>
				<li>Connects all your microservices with built-in service discovery</li></br>
				<li>Makes scaling your cluster to just the right size easy so you save money on your cloud bills</li>
			</ul>		
		</p>

		<center><button>Try Flynn Now</button></center>

	</div>

	<div>
		
		<h2>Whatever you need,</br>
Flynn can help.</h2>

	<h3>Getting apps running in the cloud
is way too hard.</h3>

	<article>
		 Deployment. Ops. Databases. Containers. Configuration management. Service discovery. Forget about all of them.
		</br>
		</br>
Flynn is all you need to know.
		</br>
		</br>
Flynn is a simple, turnkey solution to cloud, containers, ops, whatever you want to call it. Flynn manages all the technology you need under the surface. So you get all the benefits with none of the work or complexity.
		</br>
		</br>
Get back to writing your app and running your business.
		</br>
		</br>
And Flynn gets better everyday. We track the infrastructure space closely and regularly integrate new components and features, so you get the best technology without having to figure out how everything fits together.
		</br>
		</br>
And like all good things, it's completely free. 

	<h3>Growth is hard.</h3>

 Users love your product and you're growing like crazy. Your engineering team is already stretched thin keeping up with growth.
		</br>
		</br>
You're using more cloud instances, apps, containers, languages, frameworks, and databases.
		</br>
		</br>
Your ops team (if you have one) is already under water trying to keep up.
		</br>
		</br>
Flynn helps you breeze through those challenges.
		</br>
		</br>
Developers can deploy with a single command straight from git. Operators manage a single platform instead of doing custom work before each app can be deployed.
		</br>
		</br>
Databases manage themselves. Service discovery, scheduling, containers, routing, and cluster management are all taken care of in the background.
		</br>
		</br>
<h3>Your world is changing too quickly.</h3>
		</br>
		</br>
New languages, frameworks, version control systems, databases, architectures, and other bleeding-edge technologies are taking over, fast.
		</br>
		</br>
You need containers, microservices, polyglot everything, and cost savings yesterday.
		</br>
		</br>
Developers need the best tools for the job in a changing world. Operators and IT teams need a platform they can manage instead of building everything from scratch, one piece at a time.
		</br>
		</br>
Flynn has you covered. All the shiny new best practices in a single turnkey solution.
		</br>
		</br>
It's free and open source so you can have tomorrow's technology today without any lock-in.
		</br>
		</br>
<h3>We can run it for you.</h3>
		</br>
		</br>
You can run Flynn yourself or our experienced team can install, run, and manage a Flynn cluster for you. We work with your developers to help you get the most out of Flynn and your apps. And since Flynn is 100% open source there's no lock-in.
		</br>
		</br>
We can also support your ops, IT, or sysadmins team 24/7 if you prefer to handle things yourself but still want help on call.
lock-in.
		</br>
		</br>
<center><button>Try Flynn Now</button></center>
</article>
</div>
<center><div class="mail">
		<h2>Mailing List</h2>
      <form>
  <label>Email Address&nbsp;
    <input name="EMAIL" placeholder="you@example.com" type="email">
  </label>
  <button type="submit" name="subscribe">Subscribe</button>
</form>
	</div></center>

</section>

	<footer>
		<ul>
		<ol>Get the source on GitHub.</ol>
			<ol>Join us on IRC</ol>
			<ol>Follow us on Twitter.</ol>
			<ol>Read the docs.</ol>
			<ol>Get some swag.</ol>
			<ol>Email us.</ol>						
		</ul>

	</footer>

app/views/home/page_accueil.html.erb
<p>MES LANDING PAGES</p>


<p> <%= link_to("Checkr", home_checkr_path) %></p>

<%= link_to("Flynn", home_flynn_path) %></p>

app/views/home/sparks.html.erb
<h1>Home#sparks</h1>
<p>Find me in app/views/home/sparks.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LandingPages</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>